# Site settings
title: CloudDev
email: peter@clouddev.nl
url: http://petergerritsen.github.io/clouddev.nl
baseurl: /clouddev.nl
description: "CloudDev - A Cloud development services company offering .Net and Azure development, architecture and consultancy"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00aa88'

# Footer settings
footer: CloudDev

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pjotr80
  - title: linkedin
    url: https://nl.linkedin.com/in/petergerritsen80
  - title: github
    url: https://github.com/petergerritsen

# Build settings
markdown: kramdown
permalink: pretty
