# Site settings
title: CloudDev - Peter Gerritsen, freelance Azure and .NET developer based in Utrecht
email: peter@clouddev.nl
url: http://clouddev.nl
baseurl: 
description: "CloudDev - A Cloud development services company offering freelance .NET and Azure development, architecture and consultancy"

# Color settings
color:
  primary-dark: '#000000'
  primary-light: '#ffffff'
  blue: '#006680'
  green: '#00aa88'
  links: '#00aa88'
  links-hover: '#006680'

# Footer settings
footer: CloudDev

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://nl.linkedin.com/in/petergerritsen80
  - title: github
    url: https://github.com/petergerritsen
  - title: twitter
    url: https://twitter.com/pjotr80

# Build settings
markdown: kramdown
permalink: pretty
